### ISSUE TITLE
Configuration script assumes git is installed

### ISSUE THREAD

**Issue by CDuPlooy** [egeldenhuys/black-fitch#21]
I see now what you did with that sh script , I'm not entirely sure what the standard is but there are other ways of doing this. You could for example in the script prompt the user what compiler he or she would want to use ( the catch framework is for Objective-C , C++ and maybe C [ I found the repo :p ] ). The compiler flags don't really change when switching from g++ to clang++ for the projects we're working on and the preprocessor directives inside that enormous header file make provisions for most common compilers.

In the bash script you can test to see if git is installed by

``` bash
if [ git &> /dev/null ]
  then
 echo "Git support enabled" 
 #Append the pull target
 else
 echo "Git support disabled"
fi
```

**Comment by egeldenhuys** [comment]
It might be worth investigating the `./configure` `make` `make install` process using [GNU automake](https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html#Autotools-Introduction)

See also [The magic behind configure, make, make install - George Brocklehurst](https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install)

**Comment by egeldenhuys** [comment]
I assume the OS will prompt the user that git is not installed and then let the makefile fail, this is sufficient for me.

Anyone is welcome to add functionality for detecting or setting the default compiler. Currently this can be achieved by editing the `makefile_template`.
