### ISSUE TITLE
Automated Build System

### ISSUE THREAD

**Issue by devosray** [egeldenhuys/black-fitch#3]
I thought we could automate the process of compiling and running the tests for convenience. I made a quick prototype of this idea, see the [makefiles branch on my fork](https://github.com/devosray/black-fitch/commit/951cec2a5cc2c49255502b7925ae73964b0c358d)

This is only an idea but it works. Any ideas to improve this system?

**Comment by egeldenhuys** [comment]
I like how your method keeps the testing separate from the the implementation. It is then much harder to accidentally upload the wrong files to fitchfork.

I had to add `-std=c++11` to the CFLAGS for the test cases to compile.

When you are ready send a pull request :smile:

**Comment by devosray** [comment]
Will do
