### ISSUE TITLE
Assignment 2: Unnecessary testing.

### ISSUE THREAD

**Issue by Quantum-Sicarius** [egeldenhuys/black-fitch#30]
Fitch fork does not expect us to throw from our code, but rather to catch it and print out the error. (I know it seems silly.) I am getting full marks on Fitchfork but blackfitch is complaining about 
`thrown != true`. Not a problem but may be misleading to some users.

**Comment by egeldenhuys** [comment]
It seems I misinterpreted the specifications then. I will review the tests and the requirements.
Thank you for testing

**Comment by egeldenhuys** [comment]
It appears fitchfork is not testing for exceptions at all. I have tagged the tests to allow them to fail as expected.

**Comment by CGVanWyk** [comment]
hey I think your inheritance at zigzag.h should be class ZigZag: public virtual TranspositionCipher

**Comment by egeldenhuys** [comment]
@BestStriker, I understand that using virtual base classes are most useful when working with multiple inheritance. Virtual inheritance in this case does not seem to make a difference.

See [Virtual Base Classes Tutorial](http://www.learncpp.com/cpp-tutorial/128-virtual-base-classes/)
