### ISSUE TITLE
Legal ownership concerns

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/black-fitch#43]
I have concerns regarding the legal owner of the works created and the future of the Black Fitch project.

- Does the project in its current state violate any policies of the University or the Computer Science department?

- Who is the legal owner of Black Fitch? I vaguely remember a clause in the student contract stating all work creates while a student belongs to the University. As it stands, Black Fitch is dependent on Fitchfork assignments. 

I do not want to receive a DCMA takedown notice in the future.

If anyone has some insight into this and can reference some legal documents, that would be great.

**Comment by Quantum-Sicarius** [comment]
Some things worth reading:
http://www.cs.up.ac.za/cs/vpieterse/pub/Pieterse_CSERC13.pdf
http://www.cs.up.ac.za/cs/vpieterse/pub/SACLA2014_plagiarism.pdf

**Comment by egeldenhuys** [comment]
Extract from [University of Pretoria Intellectual Property Policy](http://www.up.ac.za/media/shared/538/ZP_Files/up-ip-policynipmo.zp68489.pdf):
> 2.1.10 Software
>
>In terms of the Copyright Act 98 of 1978, software is subject to copyright protection.
However, in certain jurisdictions software may also be patented. The development of
software by employees, contract workers and students are subject to the following
provisions:
>
> Software developed by employees, contract workers and students is subject to this
Intellectual Property Policy and the provisions of paragraphs 2.1.2, 2.1.8 and 2.2.2 apply
equally to:
>	- documents supporting the development and operation of developed software
packages shall be retained by developers and surrendered to the University upon
request; and
>	- new software development and progress therewith shall be disclosed to the
University, as is the case for all other IP. 
> 
> Open-source software
Notwithstanding the University’s claim to ownership of software that is created by its
employees, contract workers and students in their normal course and scope of their
work, the University supports and promotes the creation and participation in the creation
of open-source software. The University will not lay claim to ownership of open-source
software. However employees, contract workers and students are required to disclose to
the UP TTO their intention to create or to participate in the creation of open-source
software. The UP TTO shall evaluate the written disclosure and undertakes to discuss
within four weeks after the disclosure with the inventor, whether or not alternative means
of utilisation of the envisaged software exists. In the event where such employee,
contract worker or student fails to disclose his/her intention, the University reserves the
right to at a later stage lay claim to the copyright of such software program(s). 
UP IP Policy Page 14 of 39
Employees, contract workers and students shall familiarise themselves with the licence
conditions applicable to the application of open-source software and shall not take any
actions that might frustrate the University’s rights and ownership of the developed
software. 
>
> 2.2 STUDENTS
>
> 2.2.1 General
> 
> Unless otherwise agreed in writing beforehand between the student and the University,
students are deemed to have assigned to the University any IP that may vest in them by
virtue of the performance of their study obligations. Such assignment takes place
automatically during the registration process.
>
> 2.2.2 Specific provisions in respect of copyright
> 
> Students assign to the University their copyrights in all works that may be created in the
normal scope and course of their study obligations and activities. These include, inter
alia, all presentations, assignments, test and examination answer sheets, dissertations,
theses, sound recordings, video recordings, software, databases, designs and models
developed by students in the course of their studies. The University may decide in certain
cases to assign ownership of the whole or part of the copyright to the student, or may
authorise him/her otherwise to utilise the work commercially or otherwise. 
> 
> Software
> 
> See paragraph 2.1.10 in this regard, which applies, mutatis mutandis, to students.
