### ISSUE TITLE
Use a proper test framework

### ISSUE THREAD

**Issue by Quantum-Sicarius** [egeldenhuys/black-fitch#6]
Using something like Catch will allow tests to run without aborting on a failed test.

https://github.com/philsquared/Catch

**Comment by devosray** [comment]
We saw Catch and it looks very promising. The biggest motivation for this project is creating a drop-in integration test for the COS 110 pracs so other people can easily test their code. 

Catch is fortunately a header only implementation of a unit test framework so it is a real 
possibility, but right now we are looking at streamlining the usage process. Not everyone wants to copy and paste files around. One idea is to create our own makefiles that compiles the student's code from a few directories up. If we go with that approach, something like Catch would be very easy and handy to implement.

The other thought is to compile the test cases into a static library that you add to your makefile which includes all the tests bundled together with a main method. Catch would be easy to integrate there as well.

We are still exploring options and with the 110 Assignment coming up, I'm sure we will find something creative! Thanks for your input @Quantum-Sicarius

**Comment by egeldenhuys** [comment]
I like the idea of tests being able to fail without aborting. Will look at using a framework such as Catch for Assignment 1
