### ISSUE TITLE
Incorrect expectedOutput (prac3_task2_tests.cpp)

### ISSUE THREAD

**Issue by Jtfnel** [egeldenhuys/black-fitch#7]
The createMockLibraryPrintOutput(...) function on line 139 contains an error on line 143 where it is generating the expected output.
- Mistake: expectedOutput << "Inventory of " << libraryName << endl;
- Corrected: expectedOutput << "Inventory of " << libraryName << ":" << endl;

There is a missing colon that is required in the example provided by the University.

**Comment by devosray** [comment]
Good spot

While the specification does show a colon at the end of the library name, it is not strictly required by Fitch-fork. My implementation does not output the colon but I got no complaints from fitchfork

**Comment by Jtfnel** [comment]
I was a bit nervous about uploading it to fitchfork without the colon but it's good to know that it works without it, thanks!
