### ISSUE TITLE
Suggestion: Use regex for string matching

### ISSUE THREAD

**Issue by devosray** [egeldenhuys/black-fitch#8]
From issue #7 it seems like Fitch-fork does not always check the output character by character. Maybe we could rather use regex to parse the output string so we can optionally check for characters? 

The check referred to by issue #7 could be replaced by the following regex expression:
`"Inventory of  (libraryName):?\n"`

C++11 has a [built in regex library ](http://www.cplusplus.com/reference/regex/)so it is definitely doable

**Comment by egeldenhuys** [comment]
Will make use of regex for future tests where fitchfork is not so strict on the output. For example when it simply looks for a certain string in the output.

Thank you for the regex links.
